/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R1RouteImport } from './routes/1'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsTranscribeRouteImport } from './routes/tools.transcribe'
import { Route as ToolsSrtRouteImport } from './routes/tools.srt'
import { Route as ToolsBilingualRouteImport } from './routes/tools.bilingual'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as AccountEmailChangeVerifyRouteImport } from './routes/account.email-change.verify'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const R1Route = R1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTranscribeRoute = ToolsTranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSrtRoute = ToolsSrtRouteImport.update({
  id: '/srt',
  path: '/srt',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBilingualRoute = ToolsBilingualRouteImport.update({
  id: '/bilingual',
  path: '/bilingual',
  getParentRoute: () => ToolsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEmailChangeVerifyRoute =
  AccountEmailChangeVerifyRouteImport.update({
    id: '/email-change/verify',
    path: '/email-change/verify',
    getParentRoute: () => AccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/account': typeof AccountRouteWithChildren
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tools/bilingual': typeof ToolsBilingualRoute
  '/tools/srt': typeof ToolsSrtRoute
  '/tools/transcribe': typeof ToolsTranscribeRoute
  '/tools/': typeof ToolsIndexRoute
  '/account/email-change/verify': typeof AccountEmailChangeVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/account': typeof AccountRouteWithChildren
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tools/bilingual': typeof ToolsBilingualRoute
  '/tools/srt': typeof ToolsSrtRoute
  '/tools/transcribe': typeof ToolsTranscribeRoute
  '/tools': typeof ToolsIndexRoute
  '/account/email-change/verify': typeof AccountEmailChangeVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/account': typeof AccountRouteWithChildren
  '/app': typeof AppRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tools': typeof ToolsRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tools/bilingual': typeof ToolsBilingualRoute
  '/tools/srt': typeof ToolsSrtRoute
  '/tools/transcribe': typeof ToolsTranscribeRoute
  '/tools/': typeof ToolsIndexRoute
  '/account/email-change/verify': typeof AccountEmailChangeVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1'
    | '/account'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/insights'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/tools'
    | '/sessions/$sessionId'
    | '/tools/bilingual'
    | '/tools/srt'
    | '/tools/transcribe'
    | '/tools/'
    | '/account/email-change/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1'
    | '/account'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/insights'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/sessions/$sessionId'
    | '/tools/bilingual'
    | '/tools/srt'
    | '/tools/transcribe'
    | '/tools'
    | '/account/email-change/verify'
  id:
    | '__root__'
    | '/'
    | '/1'
    | '/account'
    | '/app'
    | '/demo'
    | '/forgot-password'
    | '/insights'
    | '/privacy-policy'
    | '/reset-password'
    | '/terms-of-service'
    | '/tools'
    | '/sessions/$sessionId'
    | '/tools/bilingual'
    | '/tools/srt'
    | '/tools/transcribe'
    | '/tools/'
    | '/account/email-change/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1Route: typeof R1Route
  AccountRoute: typeof AccountRouteWithChildren
  AppRoute: typeof AppRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1': {
      id: '/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/transcribe': {
      id: '/tools/transcribe'
      path: '/transcribe'
      fullPath: '/tools/transcribe'
      preLoaderRoute: typeof ToolsTranscribeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/srt': {
      id: '/tools/srt'
      path: '/srt'
      fullPath: '/tools/srt'
      preLoaderRoute: typeof ToolsSrtRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/bilingual': {
      id: '/tools/bilingual'
      path: '/bilingual'
      fullPath: '/tools/bilingual'
      preLoaderRoute: typeof ToolsBilingualRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/email-change/verify': {
      id: '/account/email-change/verify'
      path: '/email-change/verify'
      fullPath: '/account/email-change/verify'
      preLoaderRoute: typeof AccountEmailChangeVerifyRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountEmailChangeVerifyRoute: typeof AccountEmailChangeVerifyRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountEmailChangeVerifyRoute: AccountEmailChangeVerifyRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ToolsRouteChildren {
  ToolsBilingualRoute: typeof ToolsBilingualRoute
  ToolsSrtRoute: typeof ToolsSrtRoute
  ToolsTranscribeRoute: typeof ToolsTranscribeRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsBilingualRoute: ToolsBilingualRoute,
  ToolsSrtRoute: ToolsSrtRoute,
  ToolsTranscribeRoute: ToolsTranscribeRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1Route: R1Route,
  AccountRoute: AccountRouteWithChildren,
  AppRoute: AppRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsightsRoute: InsightsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ToolsRoute: ToolsRouteWithChildren,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
